language: python
python:
  - "2.7"
sudo: required

install:
  - sudo pip install ansible mkdocs
  - echo localhost >> settings.ini
  - ansible-galaxy install -r ansible/roles.txt

script:
  - sudo ssh-keygen -t rsa -f /root/.ssh/id_rsa -N "" -q
  - sudo bash -c "cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys"
  - sudo bash -c "ssh-keyscan -t rsa -H $(hostname)  >> /root/.ssh/known_hosts"
  - sudo cat /root/.ssh/known_hosts
  - sudo ssh $(hostname) true
  - sudo ansible-playbook setup.yml -c local -e ssh_key_type=rsa
  - mkdocs build
