language: python
python:
  - "2.7"
sudo: required

install:
  - sudo pip install ansible mkdocs
  - echo localhost >> settings.ini
  - ansible-galaxy install -r ansible/requirements.yml

script:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t ecdsa -H $(hostname)  >> ~/.ssh/known_hosts
  - sudo ansible-playbook setup.yml -c local -e ssh_key_type=rsa
  - mkdocs build
