language: python
python:
  - "2.6"
  - "2.7"
sudo: required

install:
  - sudo pip install ansible mkdocs

script:
  - echo localhost >> settings.ini
  - sudo ansible-playbook setup.yml -c local -e ssh_key_type=rsa
  - mkdocs build
