language: python
python:
  - "2.6"
  - "2.7"
sudo: required

install:
  - sudo pip install ansible mkdocs
  - echo localhost >> settings.ini
  - ansible-playbook install -r ansible/roles.txt

script:
  - sudo ansible-playbook setup.yml -c local -e ssh_key_type=rsa
  - mkdocs build
