version: "2"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=${S_DB_PASSWORD}
      - APP_NAME="Fit for Git"
      - RUN_MODE=prod
      - SSH_DOMAIN=${FFG_DOMAIN}
      - ROOT_URL=http://${FFG_DOMAIN}/gitea
      - SECRET_KEY=${S_GITEA_KEY}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${S_DB_ROOT_PASSWORD}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=${S_DB_PASSWORD}
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql

  drone-server:
    image: drone/drone:latest
    networks:
      - gitea
    ports:
      - "8081:80"
    volumes:
      - ./drone:/data
    restart: always
    depends_on:
      - gitea
    environment:
      - DRONE_SERVER_HOST=${FFG_DOMAIN}
      - DRONE_SERVER_PROTO=http
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${S_DRONE_SECRET}

  drone-agent:
    image: drone/agent:latest
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - gitea
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./www:/www
    environment:
      - DRONE_RPC_SERVER=http://drone-server
      - DRONE_RPC_SECRET=${S_DRONE_SECRET}
      - FFG_DIR=${PWD}

  www:
    image: nginx:latest
    restart: always
    networks:
      - gitea
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
