site_name: Fit for Git
theme: readthedocs

repo_url: http://ffg/gogs/ffg/FitForGit
repo_name: Gogs
edit_uri: _edit/master/docs

extra_css: [ffg.css]

pages:
- Home: "index.md"
- Course:
  - "Recording Changes": "01_recording_changes.md"
  - "Central Repository": "02_central_repository.md"
  - "Branching and Merging": "03_branching_and_merging.md"
  - "Pull Requests": "04_pull_requests.md"
  - "Rewriting History": "05_rewriting_history.md"
- Repositories: "repos.md"
