site_name: Fit for Git
theme: readthedocs

pages:
- Course:
  - "Recording Changes": "01_recording_changes.md"
  - "Central Repository": "02_central_repository.md"
  - "Pull Requests": "03_pull_requests.md"
