#!/bin/sh
cat >secrets <<EOF
export FFG_DOMAIN=$(hostname)

export S_DB_PASSWORD=$(openssl rand -hex 16)
export S_DB_ROOT_PASSWORD=$(openssl rand -hex 16)
export S_GITEA_KEY=$(openssl rand -hex 16)
export S_DRONE_SECRET=$(openssl rand -hex 16)
EOF
