---
admin_user: ffg
admin_pw: fitforgit

users: [ "user1", "user2", "user3", "user4", "user5", "user6", "user7", "user8", "user9" ]
user_pw: fitforgit
user_key: ""

gogs_version: 0.10.18
gogs_user: git
